export const productsData = [
  {
    id: 1,
    title: 'Air Force',
    img: [
      'img/air-force-1.jpg',
      'img/air-force-2.jpg',
      'img/air-force-3.jpg',
      'img/air-force-4.jpg',
      'img/air-force-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: 'Air Jordan Low',
    img: [
      'img/air-jordan-low-1.jpg',
      'img/air-jordan-low-2.jpg',
      'img/air-jordan-low-3.jpg',
      'img/air-jordan-low-4.jpg',
      'img/air-jordan-low-5.jpg',
    ],
    price: 200,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: 'Air Jordan Mid',
    img: [
      'img/air-jordan-mid-1.jpg',
      'img/air-jordan-mid-2.jpg',
      'img/air-jordan-mid-3.jpg',
      'img/air-jordan-mid-4.jpg',
      'img/air-jordan-mid-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: 'Air Jordan XXXV',
    img: [
      'img/air-jordan-xxxv-1.jpg',
      'img/air-jordan-xxxv-2.jpg',
      'img/air-jordan-xxxv-3.jpg',
      'img/air-jordan-xxxv-4.jpg',
      'img/air-jordan-xxxv-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: 'Air Max 90',
    img: [
      'img/air-max-90-1.jpg',
      'img/air-max-90-2.jpg',
      'img/air-max-90-3.jpg',
      'img/air-max-90-4.jpg',
      'img/air-max-90-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: 'Blazer Low',
    img: [
      'img/blazer-low-1.jpg',
      'img/blazer-low-2.jpg',
      'img/blazer-low-3.jpg',
      'img/blazer-low-4.jpg',
      'img/blazer-low-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: 'Challenger OG',
    img: [
      'img/challenger-og-1.jpg',
      'img/challenger-og-2.jpg',
      'img/challenger-og-3.jpg',
      'img/challenger-og-4.jpg',
      'img/challenger-og-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: 'Cortez',
    img: [
      'img/cortez-1.jpg',
      'img/cortez-2.jpg',
      'img/cortez-3.jpg',
      'img/cortez-4.jpg',
      'img/cortez-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: 'D-Break',
    img: [
      'img/dbreak-1.jpg',
      'img/dbreak-2.jpg',
      'img/dbreak-3.jpg',
      'img/dbreak-4.jpg',
      'img/dbreak-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: 'Free Metcon',
    img: [
      'img/free-metcon-1.jpg',
      'img/free-metcon-2.jpg',
      'img/free-metcon-3.jpg',
      'img/free-metcon-4.jpg',
      'img/free-metcon-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: 'Kybrid',
    img: [
      'img/kybrid-1.jpg',
      'img/kybrid-2.jpg',
      'img/kybrid-3.jpg',
      'img/kybrid-4.jpg',
      'img/kybrid-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: 'Metcon',
    img: [
      'img/metcon-1.jpg',
      'img/metcon-2.jpg',
      'img/metcon-3.jpg',
      'img/metcon-4.jpg',
      'img/metcon-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: 'Metcon Training',
    img: [
      'img/metcon-training-1.jpg',
      'img/metcon-training-2.jpg',
      'img/metcon-training-3.jpg',
      'img/metcon-training-4.jpg',
      'img/metcon-training-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: 'React Infinity',
    img: [
      'img/react-infinity-1.jpg',
      'img/react-infinity-2.jpg',
      'img/react-infinity-3.jpg',
      'img/react-infinity-4.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: 'SB Zoom Blazer Mid',
    img: [
      'img/sb-zoom-blazer-mid-1.jpg',
      'img/sb-zoom-blazer-mid-2.jpg',
      'img/sb-zoom-blazer-mid-3.jpg',
      'img/sb-zoom-blazer-mid-4.jpg',
      'img/sb-zoom-blazer-mid-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: 'SB Zoom Stefan',
    img: [
      'img/sb-zoom-stefan-1.jpg',
      'img/sb-zoom-stefan-2.jpg',
      'img/sb-zoom-stefan-3.jpg',
      'img/sb-zoom-stefan-4.jpg',
      'img/sb-zoom-stefan-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: 'Space Hippie',
    img: [
      'img/space-hippie-1.jpg',
      'img/space-hippie-2.jpg',
      'img/space-hippie-3.jpg',
      'img/space-hippie-4.jpg',
      'img/space-hippie-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: 'Super REP',
    img: [
      'img/superrep-1.jpg',
      'img/superrep-2.jpg',
      'img/superrep-3.jpg',
      'img/superrep-4.jpg',
      'img/superrep-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: 'Zoom Freak',
    img: [
      'img/zoom-freak-1.jpg',
      'img/zoom-freak-2.jpg',
      'img/zoom-freak-3.jpg',
      'img/zoom-freak-4.jpg',
      'img/zoom-freak-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: 'Zoom-X Vaporfly',
    img: [
      'img/zoomx-vaporfly-1.jpg',
      'img/zoomx-vaporfly-2.jpg',
      'img/zoomx-vaporfly-3.jpg',
      'img/zoomx-vaporfly-4.jpg',
      'img/zoomx-vaporfly-5.jpg',
    ],
    price: 100,
    brand: 'Nike',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam aspernatur sint exercitationem, explicabo deserunt autem quisquam nisi, aperiam quaerat nobis, ipsam iusto qui dignissimos fugit. Deleniti aut voluptate sit. Explicabo.',
    inCart: false,
    count: 0,
    total: 0,
  },
];
